In [1]:
import pandas as pd

In [2]:
#https://www.basketball-reference.com/leagues/NBA_2010_rookies-season-stats.html

In [3]:
years = ['2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022']

In [4]:
missingLink = 'https://www.basketball-reference.com/leagues/NBA_{}_rookies-season-stats.html'
nums = [1,2,3,4,5,6,7,8,9,10,11,12,13]
df = pd.DataFrame()
for i in years:
    url = missingLink.format(i)
    for j in nums:
        df2 = pd.read_html(url, header = 0)
        df = df.append(df2)

In [5]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Totals,Totals.1,Totals.2,Totals.3,Totals.4,...,Totals.13,Totals.14,Totals.15,Shooting,Shooting.1,Shooting.2,Per Game,Per Game.1,Per Game.2,Per Game.3
0,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,TOV,PF,PTS,FG%,3P%,FT%,MP,PTS,TRB,AST
1,1,David Andersen,"Oct 27, '09, HOU @ POR",29,1,63,891,147,340,27,...,37,119,367,.432,.346,.687,14.1,5.8,3.3,0.7
2,2,Antonio Anderson,"Mar 3, '10, OKC @ DEN",24,1,1,15,1,3,0,...,1,1,2,.333,NaN,NaN,15.0,2.0,1.0,0.0
3,3,Jeff Ayres,"Dec 22, '09, POR @ DAL",22,1,39,405,43,65,0,...,12,76,104,.662,NaN,.900,10.4,2.7,2.5,0.0
4,4,Rodrigue Beaubois,"Oct 30, '09, DAL @ LAL",21,1,56,700,155,299,45,...,54,84,397,.518,.409,.808,12.5,7.1,1.4,1.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,122,Ziaire Williams,"Oct 20, '21, MEM vs. CLE",20,1,62,1346,191,424,76,...,41,113,501,.450,.314,.782,21.7,8.1,2.1,1.0
135,123,McKinley Wright IV,"Oct 20, '21, MIN vs. HOU",23,1,5,19,2,3,1,...,1,1,5,.667,.500,NaN,3.8,1.0,0.0,0.6
136,124,Moses Wright,"Dec 22, '21, LAC @ SAC",23,1,4,14,1,4,0,...,0,0,5,.250,.000,1.000,3.5,1.3,0.8,0.5
137,125,Gabe York,"Apr 9, '22, IND @ PHI",28,1,2,21,2,7,1,...,1,4,8,.286,.167,.600,10.5,4.0,1.0,2.0
138,126,Omer Yurtseven,"Oct 21, '21, MIA vs. MIL",23,1,56,706,130,247,1,...,41,84,299,.526,.091,.623,12.6,5.3,5.3,0.9

In [6]:
df[df.Totals == 'G']

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Totals,Totals.1,Totals.2,Totals.3,Totals.4,...,Totals.13,Totals.14,Totals.15,Shooting,Shooting.1,Shooting.2,Per Game,Per Game.1,Per Game.2,Per Game.3
0,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,TOV,PF,PTS,FG%,3P%,FT%,MP,PTS,TRB,AST
22,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,TOV,PF,PTS,FG%,3P%,FT%,MP,PTS,TRB,AST
44,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,TOV,PF,PTS,FG%,3P%,FT%,MP,PTS,TRB,AST
0,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,TOV,PF,PTS,FG%,3P%,FT%,MP,PTS,TRB,AST
22,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,TOV,PF,PTS,FG%,3P%,FT%,MP,PTS,TRB,AST
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,TOV,PF,PTS,FG%,3P%,FT%,MP,PTS,TRB,AST
66,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,TOV,PF,PTS,FG%,3P%,FT%,MP,PTS,TRB,AST
88,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,TOV,PF,PTS,FG%,3P%,FT%,MP,PTS,TRB,AST
110,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,TOV,PF,PTS,FG%,3P%,FT%,MP,PTS,TRB,AST
132,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,3P,...,TOV,PF,PTS,FG%,3P%,FT%,MP,PTS,TRB,AST

In [7]:
df = df.drop(df[df.Totals == 'G'].index)

In [8]:
df[df.Totals == 'G']

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Totals, Totals.1, Totals.2, Totals.3, Totals.4, Totals.5, Totals.6, Totals.7, Totals.8, Totals.9, Totals.10, Totals.11, Totals.12, Totals.13, Totals.14, Totals.15, Shooting, Shooting.1, Shooting.2, Per Game, Per Game.1, Per Game.2, Per Game.3]
Index: []

[0 rows x 28 columns]

In [9]:
data = pd.read_csv('/Users/vishva/CollegeBasketballPlayers2009-2021.csv')
data

/Users/vishva/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (27) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,player_name,team,conf,GP,Min_per,Ortg,usg,eFG,TS_per,ORB_per,...,dgbpm,oreb,dreb,treb,ast,stl,blk,pts,Unnamed: 64,Unnamed: 65
0,DeAndrae Ross,South Alabama,SB,26,29.5,97.3,16.6,42.5,44.43,1.6,...,-1.941150,0.1923,0.6154,0.8077,1.1923,0.3462,0.0385,3.8846,NaN,6.22026
1,Pooh Williams,Utah St.,WAC,34,60.9,108.3,14.9,52.4,54.48,3.8,...,-0.247934,0.6765,1.2647,1.9412,1.8235,0.4118,0.2353,5.9412,NaN,3.94375
2,Jesus Verdejo,South Florida,BE,27,72.0,96.2,21.8,45.7,47.98,2.1,...,-0.883163,0.6296,2.3333,2.9630,1.9630,0.4815,0.0000,12.1852,NaN,10.92680
3,Mike Hornbuckle,Pepperdine,WCC,30,44.5,97.7,16.0,53.6,53.69,4.1,...,-0.393459,0.7000,1.4333,2.1333,1.1000,0.5667,0.1333,4.9333,NaN,6.77427
4,Anthony Brown,Pacific,BW,33,56.2,96.5,22.0,52.8,54.31,8.3,...,-0.668318,1.4242,3.3030,4.7273,0.8485,0.4545,0.3333,7.5758,NaN,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61056,Trey Patterson,Villanova,BE,2,0.3,60.5,19.3,0.0,0.00,0.0,...,16.018200,0.0000,0.0000,0.0000,0.5000,0.5000,0.0000,0.0000,Pure PG,0.00000
61057,Stavros Polatoglou,Northwestern St.,Slnd,4,1.3,28.3,7.1,0.0,0.00,7.0,...,-4.993820,0.2500,0.0000,0.2500,0.0000,0.0000,0.0000,0.0000,C,0.00000
61058,Sandy Ryan,Tulane,Amer,1,0.1,0.0,0.0,0.0,0.00,0.0,...,-1.126810,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,PF/C,0.00000
61059,Ty Larson,Texas Tech,B12,1,0.1,0.0,0.0,0.0,0.00,0.0,...,-2.380750,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,PF/C,0.00000
61060,Jaden Jones,Rutgers,B10,4,1.0,89.6,28.8,25.0,25.00,10.3,...,-3.329310,0.2500,0.0000,0.2500,0.7500,0.0000,0.0000,0.7500,Pure PG,10.43920

In [10]:
df.to_csv('/Users/vishva/Rookie_Performance.csv')